source "https://rubygems.org"

# Salut ! C'est ici que vous gérez la version de Jekyll utilisée pour exécuter le site.
# Si vous voulez utiliser une autre version, modifiez-la ci-dessous, sauvegardez le
# fichier et exécutez `bundle install`. Lancez Jekyll avec `bundle exec`, comme ceci :
#
#     bundle exec jekyll serve
#
# Cela permettra de s'assurer que la bonne version de Jekyll est utilisée.
# Bon Jekylling !

# gem "jekyll", "~> 4.3.4"  # Décommentez pour forcer une version spécifique de Jekyll

# Thème par défaut pour les nouveaux sites Jekyll. Vous pouvez le changer si vous voulez.
gem "just-the-docs"

# Si vous voulez utiliser GitHub Pages, supprimez la ligne ci-dessus pour Jekyll
# et décommentez celle ci-dessous. Pour mettre à jour, exécutez `bundle update github-pages`.
gem "github-pages", "~> 232", group: :jekyll_plugins

# Si vous avez des plugins, ajoutez-les ici !
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows et JRuby n'incluent pas les fichiers zoneinfo, donc inclure la gem tzinfo-data
# et sa bibliothèque associée.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Accélérateur de performance pour la surveillance des dossiers sur Windows
gem "wdm", "~> 0.1", platforms: [:mingw, :x64_mingw, :mswin]

# Verrouiller la gem `http_parser.rb` à la version `0.6.x` sur JRuby,
# car les versions plus récentes n'ont pas d'équivalent Java.
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]
